---
- name: Create challenge group
  group:
    name: "{{ flag_group }}"
    state: present

- name: Create flag user
  user:
    name: "{{ flag_user }}"
    group: "{{ flag_group }}"
    create_home: False

- name: Create challenge directory
  file:
    path: "{{ challenges_root_path }}/{{ challenge_name }}"
    state: directory
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"
    mode: 0750

- name: Copy challenge source
  copy:
    src: challenge.py
    dest: "{{ challenge_root }}/{{ challenge_name }}.py"
    owner: "{{ flag_user }}"
    group: "{{ flag_group }}"  
    mode: 0700

- name: Copy challenge README
  copy:
    src: README.txt
    dest: "{{ challenge_root }}/README.txt"
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"  
    mode: 0740

- name: Copy challenge systemd service
  template:
    src: "randex.service"
    dest: "/lib/systemd/system/{{ challenge_name }}.service"
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"  
    mode: 0750

- name: systemd reload configs
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: "{{ challenge_name }}.service"

