---
- name: Create challenge group
  group:
    name: "{{ flag_group }}"
    state: present

- name: Create flag user
  user:
    name: "{{ flag_user }}"
    group: "{{ flag_group }}"
    create_home: False

- name: Create challenge directory
  file:
    path: "{{ challenges_root_path }}/{{ challenge_name }}"
    state: directory
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"
    mode: 0750

- name: Create flag file
  copy:
    src: flag.txt
    dest: "{{ flag_path }}"
    owner: "{{ flag_user }}"
    group: "{{ flag_user }}"
    mode: 0600

- name: Install nmap
  apt:
    name: nmap
    update_cache: yes

- name: Set nmap permissions
  file:
    path: /usr/bin/nmap
    owner: "{{ flag_user }}"
    group: "{{ flag_user }}"
    mode: "4755"
