---
- name: Create challenge group
  group:
    name: "{{ flag_group }}"
    state: present

- name: Create flag user
  user:
    name: "{{ flag_user }}"
    group: "{{ flag_group }}"
    create_home: False

- name: Create challenge directory
  file:
    path: "{{ challenges_root_path }}/{{ challenge_name }}"
    state: directory
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"
    mode: 0750

- name: Create flag file
  copy:
    src: flag.txt
    dest: "{{ flag_path }}"
    owner: "{{ flag_user }}"
    group: "{{ flag_group }}"
    mode: 0600

- name: Copy challenge source
  template:
    src: challenge.j2
    dest: "/etc/sudoers.d/{{ challenge_name }}"
    owner: "root"
    group: "root"
    mode: 0440

- name: Enable sudo execute for other
  file:
    path: "/usr/bin/sudo"
    mode: "o=+rx"

- name: Ensure the ctf group can solve this challenge in sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ challenge_name }}"
    regexp: "^%ctf"
    line: "%ctf ALL=({{ flag_user }}) NOPASSWD: /bin/more"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0440
