---
- name: Create challenge group
  group:
    name: "{{ flag_group }}"
    state: present

- name: Create flag user
  user:
    name: "{{ flag_user }}"
    group: "{{ flag_group }}"
    create_home: False

- name: Create challenge directory
  file:
    path: "{{ challenges_root_path }}/{{ challenge_name }}"
    state: directory
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"
    mode: 0750

- name: Create flag file
  copy:
    src: flag.txt
    dest: "{{ flag_path }}"
    owner: "{{ flag_user }}"
    group: "{{ flag_group }}"
    mode: 0600

- name: Install packages
  apt:
    name: ['binfmt-support', 'gcc-mips-linux-gnu']
    update_cache: yes

- name: Configure QEMU binfmt for MIPS
  shell: |
    mkdir -p /etc/qemu-binfmt
    ln -f -s /usr/mips-linux-gnu /etc/qemu-binfmt/mips

- name: Copy the mips binfmt handler
  copy:
    src: "qemu-mips"
    dest: "/usr/share/binfmts/qemu-mips"
    owner: root
    group: root
    mode: 0644

- name: Install binfmt handler
  command: "update-binfmts --import"

- name: Copy challenge source
  copy:
    src: challenge.c
    dest: "{{ challenge_root }}/spim.c"
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"  
    mode: 0740

- name: Build challenge
  shell: |
    mips-linux-gnu-gcc spim.c -o spim -z noexecstack -Wl,-z,relro,-z,now -pie -fPIE -s
    chown "{{ flag_user }}":"{{ ctf_group }}" spim
    chmod 4750 spim
  args:
    chdir: "{{ challenge_root }}"
