---
- name: Create challenge group
  group:
    name: "{{ flag_group }}"
    state: present

- name: Create flag user
  user:
    name: "{{ flag_user }}"
    group: "{{ flag_group }}"
    create_home: False

- name: Create challenge directory
  file:
    path: "{{ challenges_root_path }}/{{ challenge_name }}"
    state: directory
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"
    mode: 0750

- name: Create flag file
  copy:
    src: flag.txt
    dest: "{{ flag_path }}"
    owner: "{{ flag_user }}"
    group: "{{ flag_group }}"
    mode: 0600

- name: Copy challenge source
  copy:
    src: challenge.c
    dest: "{{ challenge_root }}/{{ challenge_name }}.c"
    owner: "{{ flag_user }}"
    group: "{{ ctf_group }}"  
    mode: 0750

- name: Build challenge
  shell: |
    gcc "{{ challenge_name }}.c" -o "{{ challenge_name }}"
    chown "{{ flag_user }}":"{{ ctf_group }}" "{{ challenge_name }}"
    chmod 4750 "{{ challenge_name }}"
  args:
    chdir: "{{ challenge_root }}"

- name: Remove challenge source code
  file:
    path: "{{ challenge_root }}/{{ challenge_name }}.c"
    state: absent

- name: sysctl follow symlinks
  sysctl:
    name: fs.protected_symlinks
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
